import { Card } from "@/components/ui/card";
import { councilResources } from "@/lib/data/council";

export default function ResourcesPage() {
  return <div className="mx-auto max-w-7xl"><header><p className="text-sm font-semibold text-[var(--council-accent-strong,#956000)]">Resource oversight</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--council-ink)] sm:text-4xl">Candidate resources</h1><p className="mt-2 text-sm text-[var(--muted)]">Eligibility gates are applied before scores determine selection order.</p></header>
    <div className="mt-7 overflow-hidden rounded-3xl border border-[var(--border)] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-left text-sm"><thead className="bg-[var(--surface-muted)] text-xs text-[var(--muted)]"><tr><th className="px-5 py-4 font-medium">Resource</th><th className="px-5 py-4 font-medium">Status</th><th className="px-5 py-4 font-medium">Capacity</th><th className="px-5 py-4 font-medium">Network</th><th className="px-5 py-4 font-medium">Equity</th><th className="px-5 py-4 text-right font-medium">Score</th></tr></thead><tbody>{councilResources.map(resource=><tr key={resource.id} className="border-t border-[var(--border)]"><td className="px-5 py-4"><p className="font-semibold">{resource.name}</p><p className="mt-1 text-xs text-[var(--muted)]">{resource.id} · {resource.type}</p></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${resource.status==="available"?"bg-emerald-100 text-emerald-900":"bg-amber-100 text-amber-900"}`}>{resource.status.replace("_"," ")}</span></td><td className="px-5 py-4 font-mono">{resource.capacityKwh} kWh</td><td className="px-5 py-4 font-mono">{resource.network}</td><td className="px-5 py-4 font-mono">{resource.equity}</td><td className="px-5 py-4 text-right"><span className="rounded-full bg-[var(--council-ink)] px-3 py-1 font-mono font-semibold text-white">{resource.score}</span></td></tr>)}</tbody></table></div></div>
    <Card className="mt-5"><h2 className="text-lg font-semibold">How scoring works</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Consent, location, compatibility, availability, comfort and safety are hard gates. Only resources that pass are scored for network effectiveness, equity need, controllability and rotation fairness. A score sets selection order—it does not determine delivered energy.</p></Card>
  </div>;
}
